services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: discordkey
        value: YOUR_BOT_TOKEN_HERE
